### ISSUE TITLE
Don't throw general Exception

### ISSUE THREAD

**Issue by Don42** [kisom/pypcapfile#18]
The library should only throw specific exceptions and not the "base" Exception, since that makes
it difficult to differentiate where an exception comes from.

I usually define one Exception class as a base exception of the package and specific exceptions inherit from that.

Are there any problems with this implementation?
I would do the change if there aren't.

**Comment by kisom** [comment]
This is fine by me, though I might consider trying to derive from standard errors like `TypeError` where applicable.

**Comment by Don42** [comment]
I often want to catch all exceptions from a given module/package for logging purposes. A single 
base exception for the module makes this a lot easier and cleaner. This is also the behavior  mentioned in the documentation.
https://docs.python.org/3/tutorial/errors.html#user-defined-exceptions

```
try:
    # Do stuff
except pypcapfile.Error as e:
    logger.error(e)
```

**Comment by kisom** [comment]
That works.

**Comment by Don42** [comment]
Since both this and issue #12 would require breaking changes, I would propose adding them to a milestone for version 0.12.0.
I should have the time this week to fix this.

**Comment by kisom** [comment]
Sounds good, I appreciate you taking the time to fix this.
