### ISSUE TITLE
Non-hexlify everything

### ISSUE THREAD

**Issue by cristiklein** [kisom/pypcapfile#43]
Hello,

I recently needed to process a 2.3 GB pcap file, which initially took 186 s. Upon profiling, I realised that a lot of time was spent in hexlify/unhexlify, both on pcap's side as well as on my side. I felt this was both ugly and inefficient, so I checked what it means to eliminate all hexlification everywhere. The processing time decreased to 81 s, i.e., **performance more than doubled**. (see https://github.com/cristiklein/pypcapfile/commit/e29d084c66240469d4e741940ff4b7b540a6b86b)

I could spend some time rebasing my branch on top of pycapfile's current master, but before investing this time, I wanted to check if you are okey breaking the API for both performance improvement and a more intuitive API.

Regards,
Cristian

**Comment by kisom** [comment]
I'm fine with this; we can cut a breaking change API release. It's about time for a 1.0 release, anyhow :)
