### ISSUE TITLE
Cannot load pcap files split by editcap

### ISSUE THREAD

**Issue by RyuAsuka** [kisom/pypcapfile#51]
I have a large pcap file so I split it by editcap. However when I use pypcapfile to load the split file, it returns an exception

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "d:\anaconda3\envs\network\lib\site-packages\pcapfile\savefile.py", line 130, in load_savefile
    header = _load_savefile_header(input_file)
  File "d:\anaconda3\envs\network\lib\site-packages\pcapfile\savefile.py", line 105, in _load_savefile_header
    raise UnknownMagicNumber("No supported Magic Number found")
pcapfile.UnknownMagicNumber: No supported Magic Number found
```

How can I read split pcap files by this tool?

**Comment by Don42** [comment]
From what I can tell `editcap` by default uses the `pcapng` file format. Which this library does not yet support (#15).
You can try to use `-F pcap` to ask `editcap` to write the output in the old format.

Please get back to use either way and tell use the result. Feel free to close issue after doing so.

https://www.wireshark.org/docs/man-pages/editcap.html

**Comment by RyuAsuka** [comment]
Thank you very much. After I add the parameter `-F pcap` in `editcap` then the `pcapfile` tool can read the split files.
I remember it.
